### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by PhearZero** [HospitalRun/hospitalrun#14]
## 🚀 Feature Proposal

[Create React App(CRA)](https://github.com/facebook/create-react-app) Frontend

## Motivation

Use react-scripts interface to manage the Hospital Run Frontend. This should include service/state/interface injections from #12 

#### Codegen
Route based generation. Use schema extensions to map routes to components

### Getting started With CRA:
```
git clone --branch next https://github.com/HospitalRun/hospitalrun-frontend.git
npx create-react-app hospitalrun-frontend
cd hospitalrun-frontend
npm start
```
### Codegen:
```
# mono repo runs codegen then creates
# ./packages/hospitalrun-frontend/src/routes/index.tsx
#  In the Frontend
import {Router} from './routes' // Fully loaded router from spec
```

# Blocking Issues:
- [ ] HospitalRun/hospitalrun-frontend#1619

**Comment by tehKapa** [comment]
@jackcmeyer can we close this?

**Comment by jackcmeyer** [comment]
@tehKappa yes
