### ISSUE TITLE
Migrate to Yarn 2

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun#142]
Test and verify that version 2 is compatible with our monorepo and that all the features used (yarn workspace) work without problems

Some migration tips: https://next.yarnpkg.com/advanced/migration
Yarn 2 announcement: https://dev.to/arcanis/introducing-yarn-2-4eh1

**Comment by fox1t** [comment]
We can put on hold this issue for the moment. Apparently we can’t use yarn v2 anytime soon. It doesn’t use node_modules at all and instead it uses a newly developed feature called PnP that doesn’t even works (and it’s just one example) with typescript and some other tools we use.
References: https://yarnpkg.com/lang/en/docs/pnp/, https://github.com/yarnpkg/berry/issues/766
