### ISSUE TITLE
React PWA Support

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun#160]
## 🚀 Feature Proposal

Support Progressive Web Apps for React.

## Motivation

offline first

**Comment by fox1t** [comment]
We need to add also a menu entry to handle this. Something like: "Install HR". For a reference we can look at
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/1620916/73162087-51155200-40ed-11ea-9352-610727bf16d8.png">

https://bioimagesuiteweb.github.io/webapp/index.html
