### ISSUE TITLE
improve(abstraction): Create a Person type

### ISSUE THREAD

**Issue by ocBruno** [HospitalRun/hospitalrun#179]
## 🚀 Feature Proposal

Add a person type to be extended by various persons such as Patient, RelatedPerson, Doctor and future variations of person.

## Motivation

 I saw that relatedperson was of type patient but I'm not sure we should set this restriction unless necessary considering there might be cases of relatedperson which aren't patients. Also with a person type we could set common traits for person, remove code repetition, and improve the code organization and separation of concerns.

## Example

Patient extends Person
RelatedPerson extends Person
Doctor extends Person
Recepcionist extends Person

**Comment by ocBruno** [comment]
@jackcmeyer @fox1t @irvelervel @tehKapa 

Hello everyone please give me a heads up if there are any patterns that can be improved upon or if this feature isn't viable. I'm slowly refactoring things to include a base Person class and accomodate better for future person types.

**Comment by tehKapa** [comment]
In my opinion, medical staff aren't an extension of the person... but they will have to be managed as login users, and that's it (they will have to be saved in a separate database).

**Comment by ocBruno** [comment]
I was thinking of abstracting every type of person to a base person class with optional common characterstics such as name, sex etc. While creating higher level classes for different types of people such as patients doctors and users. I believe any type of person is an extension of a person but considering my lack of expertise I will leave this to be decided by the team and will close this for now. Thanks for the feedback!
