### ISSUE TITLE
how to install my project and how to build , which package to choose?

### ISSUE THREAD

**Issue by aboessa** [HospitalRun/hospitalrun#21]
## 💬 Questions and Help
Hello
i want to install a version of hospitalrun to start develop my own app, but i don`t know what a repo should i use to install on windows ,
and want to know how to develop then build my own app with electron container ?
can you help ?
### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into our [Spectrum channel](https://spectrum.chat/hospitalrun) and ask any questions you have or mention any problems you've had getting started with HospitalRun.

**Comment by tehKapa** [comment]
Hi. This monorepo is related to version 2 (still under development). 
You are probably looking for version 1.0.0-beta. You can find the relative branches on hospitalrun-frontend and hospitalrun-server.
