### ISSUE TITLE
Standardize Linting/Formatting Tools Across all Projects 

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun#23]
## 🚀 Feature Proposal

Standardize Formatting/Linting tools across code repositories:

- [x] Choose a Linting Style Guide from ESLint
- [x] Configure Prettier to work with Linting Style Guide
- [x] Ensure Linter works with VSCode Autoformatting Tools
- [x] Implement Linter/Prettier to work in frontend, backend, components.

**Comment by fox1t** [comment]
I’ll add also the point that will ensure that all the configurations works also if monorepo is used as project root. Prettier and eslint on VS Code needs extra care if the root of the project is a folder that contains other folders.

**Comment by tehKapa** [comment]
@fox1t, with yesterday's activity we closed this task, right?

**Comment by fox1t** [comment]
Yes. If there are still problems, we will open specific new issues to handle them.
