### ISSUE TITLE
How to create local instance of the same.

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [HospitalRun/hospitalrun#24]
I tried below command but not working,

git clone git@github.com:HospitalRun/hospitalrun.git

alternative I used is git clone https://github.com/HospitalRun/hospitalrun.git
cd hospitalrun

After that below command is not working
git submodule update --init --recursive
yarn

**Comment by fox1t** [comment]
Hi @Girishchandra-Yendargaye. What error did you get with `git@github.com:HospitalRun/hospitalrun.git`?

**Comment by Girishchandra-Yendargaye** [comment]
Seems proxy issue,Now I could run upto yarn....

But how to start local server now...

>yarn workspaces run build
yarn workspaces v1.19.1
yarn run v1.19.1
$ npm run test

> @hospitalrun/cli@1.0.0 test I:\hospitalrun\packages\cli
> echo "Error: no test specified" && exit 0

"Error: no test specified"
$ tsdx build
✓ Building modules 0 ms
✓ Creating entry file 163 ms
Done in 25.98s.
yarn run v1.19.1
$ tsdx build
'tsdx' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1

**Comment by Girishchandra-Yendargaye** [comment]
error An unexpected error occurred: "EPERM: operation not permitted, open 'I:\\hospitalrun\\packages\\cli\\node_modules\\@typescript-eslint\\experimental-utils\\node_modules\\.bin\\eslint.cmd'".

**Comment by Girishchandra-Yendargaye** [comment]
duplicate of #25

**Comment by fox1t** [comment]
Since you clarified on slack that you are trying to deploy HospitalRun and not to contribute to we will provide you help privately.
I am going to close this issue.
