### ISSUE TITLE
Bug while running yarn command

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [HospitalRun/hospitalrun#25]
Yarn version: 
  1.19.1

Node version: 
  10.15.3

Platform: 
  win32 x64

Trace: 
  Error: EPERM: operation not permitted, open 'I:\hospitalrun\packages\cli\node_modules\@typescript-eslint\experimental-utils\node_modules\.bin\eslint.cmd'

**Comment by fox1t** [comment]
Since you clarified on slack that you are trying to deploy HospitalRun and not to contribute to we will provide you help privately.
I am going to close this issue.
