### ISSUE TITLE
Adding users with different designations 

### ISSUE THREAD

**Issue by tabrza** [HospitalRun/hospitalrun#270]
## 💬 Questions and Help

Was playing around with the demo and noticed that the hr admin (hr.hospital.admin@hospitalrun.io) is unable to add new users with certain designations. Is that by design or is that only for the demo? Otherwise, would be worth adding it as an issue for version 2.0

**Comment by blestab** [comment]
Thank you for your input @tabrza , Kindly note these requirements before one can log an issue. You can join our Slack space here https://hospitalrun-slack.herokuapp.com/

> Before you submit an issue we recommend you drop into our Slack workspace and ask any questions you have or mention any problems you've had getting started with HospitalRun.
