### ISSUE TITLE
Selecting DOB

### ISSUE THREAD

**Issue by shubhangiagarwal76** [HospitalRun/hospitalrun#312]
Before you submit an issue we recommend you drop into our [Slack workspace](https://hospitalrun-slack.herokuapp.com/) and ask any questions you have or mention any problems you've had getting started with HospitalRun.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

While selecting the DOB there is no arrow for Year change. We have to go back month by month which is very tiring.

## Example
It will ease the users to select a date.

**Comment by jackcmeyer** [comment]
Closing in favor of https://github.com/HospitalRun/hospitalrun-frontend/issues/2047
