### ISSUE TITLE
Add "Request Medication" to quick create button in navbar 

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun#411]
## 🚀 Feature Proposal

Add "Request Medication" to quick create button in navbar requirement was missed when the basic medication module feature was implemented.

## Motivation

Add "Request Medication" to quick create button in navbar is required to keep the medication module in sync with other modules by having a quick add link for it in the navbar.

## Example

![image](https://user-images.githubusercontent.com/5468546/88663712-4ce9e180-d0dc-11ea-8a19-315980f391c5.png)

**Comment by blestab** [comment]
@jackcmeyer, sorry I realized while checking staging that this requirement was missed when i did the medication module work. I have since fixed this and would like to open a PR for it.

**Comment by blestab** [comment]
Wrong place to post this, see: [Add "Request Medication" to quick create button in navbar #2257](https://github.com/HospitalRun/hospitalrun-frontend/issues/2257)

**Comment by tehKapa** [comment]
No, he's fine here, then we'll move him :D

**Comment by blestab** [comment]
Oh okay :), you can put this ob my name, I have the fix for it.
