### ISSUE TITLE
Export Report Formats

### ISSUE THREAD

**Issue by codefusser** [HospitalRun/hospitalrun#454]
Before you submit an issue we recommend you drop into our [Slack workspace](https://hospitalrun-slack.herokuapp.com/) and ask any questions you have or mention any problems you've had getting started with HospitalRun.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🚀 Feature Proposal

I would like to recommend that the options to export reports should have additional formats like portable document format and spreadsheet.
## Motivation

This will allow for flexibility on how to work with the generated reports better.
## Example

Currently, reports are generated in comma separated values format.

**Comment by blestab** [comment]
> Before you submit an issue we recommend you drop into our [Slack workspace](https://hospitalrun-slack.herokuapp.com/) and ask any questions you have or mention any problems you've had getting started with HospitalRun.

Dear @codefusser , thank you for your suggestions. Kindly note of the above requirements before you can log issues.
