### ISSUE TITLE
RFC From Maintainers

### ISSUE THREAD

**Issue by JacobMGEvans** [HospitalRun/hospitalrun#455]
Greetings, 

I am coming from an OSS community "Raid Group" that started in www.kentcdodds.com/discord we essentially look for OSS repositories that we can make a big to a huge impact in a short amount of time with us all working on a task together.

What was noticed with yours is the started conversion to Testing Library, this happens to by a specialty of ours. 

Please let me know if your interested in this overhaul of your testing ecosystem from our group. 

Regards.

**Comment by tehKapa** [comment]
Hi @JacobMGEvans, thank you very much for the offer!
The current implementation is a bit messy due to the different contributions that have been participating in HR, so external help might help.
How would this task be approached by your group? 

cc @fox1t @jackcmeyer @blestab @morrme

**Comment by JacobMGEvans** [comment]
Basically, we fork the work into an Org, we open an in-progress PR for ongoing Maintainer review (we make a lot of changes 😅) and communication purposes.  Then anywhere between 5-10 people work on it over the next couple days from that start. 

For this case with the tests, we try to focus on refactoring. If we see potential improvements we will make suggestions or go over them closely with maintainers.

**Comment by tehKapa** [comment]
@fox1t @jackcmeyer @blestab do we need more info? I don't think so :D

**Comment by JacobMGEvans** [comment]
Awesome! We will generate a PR this weekend and get started 😄 

I hope to see you all in the PR comments. Let's Raid!!
