### ISSUE TITLE
Pathological test and automation 

### ISSUE THREAD

**Issue by codehangover** [HospitalRun/hospitalrun#458]
Hi,

 I would like to know if anything related to Pathological lab that you would be added in near future  which has automation so human error would be less in both the case in hospital and Pathological lab.
For eg: OCR used for adding right name and data of the patient etc.

1. In near future will you be adding on BSD system for server hosting or anyone tried on it  ?

**Comment by blestab** [comment]
Thanks @codehangover , Why don't you hop onto our [slack](https://hospitalrun-slack.herokuapp.com/) so you can tell us more about your requirements.

**Comment by codehangover** [comment]
> 
> 
> Thanks @codehangover , Why don't you hop onto our [slack](https://hospitalrun-slack.herokuapp.com/) so you can tell us more about your requirements.

I am sorry I can't but yes can be discussed out here so anyone having their thoughts can place it as well.
