### ISSUE TITLE
"Try on function" 

### ISSUE THREAD

**Issue by Sofiiasv** [HospitalRun/hospitalrun#461]
## 💬 

Hi everyone! When you want to try the Hospital Run demo version it's a bit confusing and inconvenient how to sign in. It would be way better if we could come up with a different approach and/or at least make sure that text explaining what we need to do (copy and paste process) is bold and big, clear enough so there is no confusion along the way. Because most of the users are not coming from professional in tech background and they need a simple and convenient way to figure out stuff. Also, that would be fantastic if we get a chance to come up with a solution to eliminate "copy-paste" and make it easier for people. Thank You! 
<img width="1440" alt="Screen Shot 2021-03-25 at 3 19 13 PM" src="https://user-images.githubusercontent.com/74344275/112551583-7bf54780-8d7e-11eb-9505-dbc9c399fff3.png">

**Comment by matteovivona** [comment]
Could this be better?

<img width="1267" alt="Screenshot 2021-03-26 at 19 11 05" src="https://user-images.githubusercontent.com/6388707/112675136-103ad980-8e67-11eb-8853-60bd4426f762.png">

**Comment by Sofiiasv** [comment]
I think we need to remove the first top "Do to Demo" button to make people go through the credentials and actually realize that they need to use them in order to log in.

**Comment by matteovivona** [comment]
Done. Thanks for your feedback
