### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by niladrishekhar** [HospitalRun/hospitalrun#463]
with so many options I am thoroughly confused which link should I follow to install a fresh instance on my local system.

Which is the folder there is a front end, component, hospital run io, hospital run front end and a hospital run server and am thoroughly confused which one to follow - also is there a proper documentation on the same that I can refer to. 

I would really appreciate if the team can point me in the right direction.

Many thanks in advance and apologies for such a rudimentary question.

**Comment by matteovivona** [comment]
Hi. Please follow this: http://eepurl.com/c7uKJ5
